# Generated by Django 2.1.2 on 2018-10-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0002_auto_20181025_1206'),
    ]

    operations = [
    ]
