# Generated by Django 2.1.2 on 2018-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='index',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
