# Generated by Django 2.1.2 on 2018-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
