# Generated by Django 2.1.2 on 2018-11-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0002_student_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='index',
        ),
    ]
