# Generated by Django 2.1.2 on 2018-11-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0003_remove_student_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='examination',
            field=models.CharField(default='Z', max_length=1),
        ),
    ]
