# Generated by Django 2.1.2 on 2018-11-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0004_course_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='examination',
            field=models.CharField(blank=True, default='Z', max_length=1),
        ),
    ]
