# Generated by Django 2.1.2 on 2018-11-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0004_auto_20181108_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
